namespace SpriteKind {
    export const Helicopter = SpriteKind.create()
    export const Cloud = SpriteKind.create()
    export const LandingPad = SpriteKind.create()
    export const Mountain = SpriteKind.create()
    export const Tree = SpriteKind.create()
    export const Duck = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    copter.vy += -1
})
sprites.onOverlap(SpriteKind.Helicopter, SpriteKind.LandingPad, function (sprite, otherSprite) {
    sprite.setVelocity(0, 0)
    sprite.y += -2
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    copter.vx += -1
})
sprites.onOverlap(SpriteKind.Helicopter, SpriteKind.Cloud, function (sprite, otherSprite) {
    sprite.x += -1 * sprite.vx
    sprite.y += -1 * sprite.vy
    sprite.vx = 0
    sprite.vy = 0
    otherSprite.y += -1
    pause(100)
    otherSprite.y += 1
})
// Control the copter with the + pad
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    copter.vx += 1
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    copter.vy += 1
})
sprites.onOverlap(SpriteKind.Duck, SpriteKind.Duck, function (sprite, otherSprite) {
    sprite.startEffect(effects.spray, 500)
})
sprites.onOverlap(SpriteKind.Helicopter, SpriteKind.Mountain, function (sprite, otherSprite) {
    sprite.x += -1 * sprite.vx
    sprite.x += -1 * sprite.vy
    sprite.setVelocity(0, 0)
    sprite.x += -2
    pause(100)
    sprite.y += -3
    pause(100)
    sprite.x += 2
    pause(100)
    sprite.y += 3
})
let copter: Sprite = null
game.splash("Cloud Bump", "control pad flying")
scene.setBackgroundColor(9)
copter = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ......................ffff......
    .....ffff.........fffffff.......
    .......fffffffffffff............
    ...............f................
    ...............f................
    ..............ef..eee...........
    ....f.........e..eeff11.........
    ..ffffffff....eee2f.1111........
    .....f......eee222f11111........
    .....f...eee222222f11111e.......
    .....feeee22222222ff11f2e.......
    .....ee22222222222fffff2e.......
    .....e222222222222fffff2e.......
    .....ee22222222222fffff2e.......
    ......ee222222e222222ff2e.......
    .......ee22222ee2222222ee.......
    ........eeee2eee222222ee........
    ...........fe...eeeeee..........
    ...........f........f...........
    ......f....f........f.....f.....
    ......ffffffffffffffffffff......
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Helicopter)
copter.setStayInScreen(true)
// Create and place "clouds"  Sprites
let cloud1 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . 1 1 1 1 1 8 . . . . . . 
    . . . 1 1 8 8 8 1 1 1 1 1 1 . . 
    . 8 1 1 8 8 8 8 8 8 8 8 8 1 1 . 
    . 1 8 8 8 1 8 8 8 1 1 8 8 8 1 . 
    1 1 8 8 1 1 1 1 1 8 8 8 1 1 1 . 
    1 1 8 8 8 8 8 1 1 8 1 8 1 1 . . 
    . 1 1 1 1 8 8 8 8 8 8 8 1 8 . . 
    . . . . 1 1 8 8 1 1 8 8 1 . . . 
    . . . . . . 8 8 8 1 1 1 1 . . . 
    . . . . . . 1 1 1 1 . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Cloud)
cloud1.x = 20
cloud1.y = 30
let cloud2 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . 1 1 1 1 1 8 . . . . . . 
    . . . 1 1 8 8 8 1 1 1 1 1 1 . . 
    . 8 1 1 8 8 8 8 8 8 8 8 8 1 1 . 
    . 1 8 8 8 1 8 8 8 1 1 8 8 8 1 . 
    1 1 8 8 1 1 1 1 1 8 8 8 1 1 1 . 
    1 1 8 8 8 8 8 1 1 8 1 8 1 1 . . 
    . 1 1 1 1 8 8 8 8 8 8 8 1 8 . . 
    . . . . 1 1 8 8 1 1 8 8 1 . . . 
    . . . . . . 8 8 8 1 1 1 1 . . . 
    . . . . . . 1 1 1 1 . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Cloud)
cloud2.x = 50
cloud2.y = 65
let cloud3 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . 1 1 1 1 1 8 . . . . . . 
    . . . 1 1 8 8 8 1 1 1 1 1 1 . . 
    . 8 1 1 8 8 8 8 8 8 8 8 8 1 1 . 
    . 1 8 8 8 1 8 8 8 1 1 8 8 8 1 . 
    1 1 8 8 1 1 1 1 1 8 8 8 1 1 1 . 
    1 1 8 8 8 8 8 1 1 8 1 8 1 1 . . 
    . 1 1 1 1 8 8 8 8 8 8 8 1 8 . . 
    . . . . 1 1 8 8 1 1 8 8 1 . . . 
    . . . . . . 8 8 8 1 1 1 1 . . . 
    . . . . . . 1 1 1 1 . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Cloud)
cloud3.x = 100
cloud3.y = 40
let landing = sprites.create(img`
    58585858585858585858585858585858
    58585858585858585858585858585858
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.LandingPad)
landing.y = 125
let mountain = sprites.create(assets.image`Mountain`, SpriteKind.Mountain)
mountain.setPosition(140, 107)
let Tree = sprites.create(assets.image`Tree`, SpriteKind.Cloud)
Tree.setPosition(18, 101)
let Duck = sprites.create(assets.image`Duck`, SpriteKind.Player)
Duck.setPosition(130, 63)
